### ISSUE TITLE
NAS Client and Desktop Client do not connect automatically

### ISSUE THREAD

**Issue by janstuemmel** [jul13579/le-lan-launcher#35]
Would appreciate more details on how to setup the launcher and a nas server, as following the steps in the readme does not make the clients connect automatically. Here are my steps: 

1. Build everything from source on linux
2. Copied the syncthing binary to a remote computer in the same network
3. Start syncthing in a docker container (all ports exposed). They know about each other (i can see that in the "add cleint" dialog)
4. Start the launcher, the launcher starts syncthing. **No items in NAS dialog**

**Comment by janstuemmel** [comment]
Ok the problem is definitly my Dockerfile...

**Comment by jul13579** [comment]
Oh wow, I haven't thought this project would get attention anytime soon. I'll look into improving the documentation though 😉

**Comment by janstuemmel** [comment]
It's a pretty nice project. Consider promoting it on reddit etc...
