### ISSUE TITLE
Windows client: Library path input broken

### ISSUE THREAD

**Issue by janstuemmel** [jul13579/le-lan-launcher#36]
I compiled a version of le launcher for windows. After installing and starting it, i can change the player name, but the directory chooser does not work. It does not save my selected folder folder. Selecting a directory in the linux client works tho.

![Bildschirmfoto_2023-01-01_22-21-51](https://user-images.githubusercontent.com/7893682/210184962-f915988e-f56d-4ca5-9568-6184a399890f.png)

OS: Win 10
Version: 1.0.4-rc.1

**Comment by janstuemmel** [comment]
I debugged into it and fixed it by removing this line: 

https://github.com/jul13579/le-lan-launcher/blob/8403f5ce83e1e9b144f10ca1236bc19a6a677e7b/src/components/SettingsView.vue#L265

**Comment by jul13579** [comment]
> I debugged into it and fixed it by removing this line:
> 
> https://github.com/jul13579/le-lan-launcher/blob/8403f5ce83e1e9b144f10ca1236bc19a6a677e7b/src/components/SettingsView.vue#L265

Can confirm. This LOC actually is some leftover of when I refactored settings view - the 'homeDirInput' ref no longer exists anywhere 🤷 I'll include this in 1.0.4-rc.2.

**Comment by jul13579** [comment]
I just pushed a few commits including this fix to `1.0.4-rc.2`. I'll therefore close this issue. If there still is anything I did miss regarding this issue, please feel free to re-open it 😉
